# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PostList_Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PostList_Demo

pod 'Alamofire'
pod 'DZNEmptyDataSet'
pod 'SwiftyJSON'

end
